### PR TITLE
Make minor corrections

### PR DESCRIPTION
**Pull request by a2937**
Add a logger so that error messages can be displayed; implement IDisposable so that there would be no confusion if Dispose gets called, and added blank lines in between property declarations so they can be read easier.

### CODE REVIEW

**Comment by a2937** [comment]
Also what do you do think of how I handled your todo of checking if the sign-in exists first?

**Comment by a2937** [comment]
I believe I might have contributed something to help fulfill the requirement of creating a CSV file and added Xunit testing. Also I believe you would probably need to a ToString method for the class that represents the visits concept.

**Comment by LeviButcher** [comment]
Can you fix these conflicts? If so then I will merge it in.

I don't think there is any use for a toString method besides maybe debugging purposes and your checks for a signIn record were good.

Thank you for contributing.

**Comment by a2937** [comment]
No problem Levi. The ToString is what the [url](https://github.com/a2937/tutor-proto/blob/master/backend/TutorPrototype/TutorPrototype/Utility/CSVFileUtil.cs) calls implicitly to join the ToString method on each collection element as per [documentation ](https://docs.microsoft.com/en-us/dotnet/api/system.string.join?redirectedfrom=MSDN&view=netframework-4.8#System_String_Join__1_System_String_System_Collections_Generic_IEnumerable___0__)

 What do you think of the merge I made? Also for debugging purposes there is a [DebuggerDisplayAttribute](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/enhancing-debugging-with-the-debugger-display-attributes) that you can add to classes to change how the classes display in the debugger only.

**Comment by a2937** [comment]
Also do you think the utility method that creates the CSV file should have an asynchronous version as well?

**Comment by LeviButcher** [comment]
I'm not for sure if it should or shouldn't. Probably since it does deal with the file system. Your changes look good so I will accept them.

**Pull request merged**
